### PR TITLE
fix(avatar-group): theme css borderRadius and rounded

### LINKED ISSUE #833: The `AvatarBadge` component references theme tokens for styling.
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

`packages/components/avatar/src/avatar-badge.tsx`
```tsx
<ui.div
  className="ui-avatar__badge__ping"
  __css={{
    position: "absolute",
    boxSize: "full",
    rounded: "full",
    opacity: 0.75,
    zIndex: -1,
    bg: pingColor,
  }}
  animation={animation}
/>
```

`packages/components/avatar/src/avatar-group.tsx`
```tsx
const {
  className,
  max,
  borderColor,
  gap = "-sm",
  borderRadius = "full",
  rounded = "full",
  children,
  ...rest
} = omitThemeProps(props)
```

`packages/components/avatar/src/avatar.tsx`

```tsx
const {
  className,
  src,
  srcSet,
  name,
  loading,
  alt,
  icon,
  ignoreFallback,
  referrerPolicy,
  borderRadius = "full",
  rounded = "full",
  onError,
  onLoad,
  crossOrigin,
  format,
  children,
  ...rest
} = omitThemeProps(mergedProps)
```

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

Yes

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by suzukisan22**
I replace from `full` to `9999px` according to [radii](https://github.com/hirotomoyamada/yamada-ui/blob/%40yamada-ui/utils%401.0.5/packages/theme/src/tokens/radii.ts#L12)

Closes #833 

# Is this a breaking change (Yes/No):
No

### CODE REVIEW

File: packages/components/avatar/src/avatar-group.tsx [hunk 1]
```diff
@@ -31,8 +31,8 @@ export const AvatarGroup = forwardRef<AvatarGroupProps, "div">((props, ref) => {
     max,
     borderColor,
     gap = "-sm",
```
Comment (suzukisan22) [inline packages/components/avatar/src/avatar-group.tsx:33]: this should be fixed, but not sure about that...

Comment (hirotomoyamada) [reply packages/components/avatar/src/avatar-group.tsx:33]: Hi, in this case, it is like this.

```diff
- gap = "-sm"
+ gap = "-0.5rem",
```

File: packages/components/avatar/src/avatar-badge.tsx [hunk 2]
```diff
@@ -125,8 +125,8 @@ export const AvatarBadge = forwardRef<AvatarBadgeProps, "div">(
             className="ui-avatar__badge__ping"
             __css={{
               position: "absolute",
-              boxSize: "full",
-              rounded: "full",
+              boxSize: "9999px",
```
Comment (hirotomoyamada) [inline packages/components/avatar/src/avatar-badge.tsx:128]:
```diff
- boxSize: "9999px",
+ boxSize: "100%",
```

**Review by hirotomoyamada — APPROVED** [review]
