### PR TITLE
fix(ripple): theme css rounded corners

### LINKED ISSUE #836: The `Ripple` component references theme tokens for styling.
### Which package has an issue?

@yamada-ui/react

### Package Version

1.2.6

### Description

Yamada UI allows you to use components without applying a theme. It is a mistake to use theme tokens inside components.

`packages/components/ripple/src/ripple.tsx`

```tsx
const css: CSSUIObject = {
  rounded: 'full',
  zIndex: 'kurillin',
};
```

### Link to Reproduction

_No response_

### Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

### Browser

None

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Do you know how to fix the issue?

None

### Are you willing to participate in fixing this issue and create a pull request with the fix?

None

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by suzukisan22**
Hi! I'm happy to try to contribute to this OSS for the first time.
We hope Yamada UI will be a success.

Closes #836 

# Description
I replace full to 9999px as maintainer pointed out
https://github.com/hirotomoyamada/yamada-ui/pull/849#discussion_r1504723288

### CODE REVIEW

File: packages/components/ripple/src/ripple.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export const Ripple: FC<RippleProps> = ({
   if (isDisabled) return null
 
   const css: CSSUIObject = {
-    rounded: "full",
+    rounded: "9999px",
     zIndex: "kurillin",
```
Comment (108yen) [inline packages/components/ripple/src/ripple.tsx:35]: PRありがとうございます！！
あの地球人も木端微塵にしてください。

```tsx
zIndex: "9"
```

**Review by 108yen — CHANGES_REQUESTED** [review]

**Review by 108yen — APPROVED** [review]
